### ISSUE TITLE
Gerbers files

### ISSUE THREAD

**Issue by ksergey** [ChrisChrisLoLo/banime40#3]
Hello!

Where to find gerbers which mentioned in [README.md](https://github.com/ChrisChrisLoLo/banime40/tree/master/pcb/banime40#gerbers)?

Thanks

**Comment by vovw** [comment]
https://github.com/ChrisChrisLoLo/banime40/blob/be7ea4e2d7a1c07467d1846ec512ee0339319960/pcb/banime40/banime40-backups/banime40-2022-04-17_230254.zip

idk why he deleted it but yeah

**Comment by ksergey** [comment]
Thanks!
